version: '2.2'
services:
 # Nginx server configuration   
  pflanzastic-client-elm:
    image: pflanzastic-client-elm
    container_name: pflanzastic-client-elm
    networks:
      pflanzastic-network:
    volumes:
      - ./public:/var/www/public
      - ./docker/container/config/nginx:/etc/nginx/conf.d/
    working_dir: /var/www/public
    ports:
      - "9090:80"

networks:
    pflanzastic-network:
